# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0e01500761c37a64bcf4ec7bc5738cd3f0e756e93faa7feb86f8aa8d4126ec3f2304aceb2e88b4718f41bcbc53e722e0cc690de9357432ad141e12f86558354

test:
  secret_key_base: 80e6c57fb393a79d087e135c3eee28074e92ae60341d766edf7cfc623a49d899380c93bd80347c54d2bb2764cfaea70e2d006fe99d88fc128a70be7b33809189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
